<BLOCK>
<LICENSE>
/*
 * (c) 2006 AUTHOR_NAME 
 */

</LICENSE>
<BLOCK_NAME>
BLOCK_NAME_REPLACE
</BLOCK_NAME> 


<DESC_SHORT>
Add short description here. Will appear in HTML documentation.
</DESC_SHORT>

<COMMENTS>
<![CDATA[ 

/*
 * 		BLOCK_NAME_REPLACE()
 *
 * Generated by blockgen
 *
 * Complex source
 * Notes:
 *    This is a block generated from the complex source template
 *    It will output numberOfSamples  of samples defined by a parameter.
 *    It outputs the complex number (1.0, -1.0) 
 *
 * 
 *    
 * Programmer: 
 * Date: 
 * Modified: 
 *
 */
]]>
</COMMENTS> 

<DECLARATIONS> 

	int i,j;
	complex sample;

</DECLARATIONS> 




<STATES>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> done </NAME>
		<VALUE> FALSE </VALUE>
	</STATE>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> sampleCount </NAME>
		<VALUE> 0 </VALUE>
	</STATE>
</STATES>



<PARAMETERS>
	<PARAM>
		<DEF> Total number of samples to output </DEF>
		<TYPE> int </TYPE>
		<NAME> numberOfSamples </NAME>
		<VALUE> 1000 </VALUE>
	</PARAM>
</PARAMETERS>



<OUTPUT_BUFFERS>
	<BUFFER>
		<TYPE> complex </TYPE>
		<NAME> x </NAME>
	</BUFFER>
</OUTPUT_BUFFERS>

<INIT_CODE>
<![CDATA[ 


]]>
</INIT_CODE> 


<MAIN_CODE>
<![CDATA[ 

	if(done)return(0);
	/* 
	 * output a maximum of NUMBER_SAMPLES samples to output buffer(s) 
	 */
	for(i=0; i < NUMBER_SAMPLES_PER_VISIT; ++i) {
	   sampleCount++;
	   if(sampleCount == numberOfSamples) {
	       done=TRUE;
	       return(0);
	   }
	   
		
	   /*
	    * ready output buffer for sample
	    * check for overflow
	    */
	   if(IT_OUT(0)) {
				KrnOverflow("BLOCK_NAME_REPLACE",0);
				return(99);
	   }
	   /*
	    * output the sample
	    */
	   sample.re=1.0;
	   sample.im= -1.0;
	   x(0)=sample;
			
			
	}

]]>
</MAIN_CODE> 

<WRAPUP_CODE>
<![CDATA[ 


]]>
</WRAPUP_CODE> 



</BLOCK> 

