<BLOCK>
<LICENSE>
/*
 * (c) 2006 AUTHOR_NAME 
 */

</LICENSE>
<BLOCK_NAME>
BLOCK_NAME_REPLACE
</BLOCK_NAME> 


<DESC_SHORT>
Add short description here. Will appear in HTML documentation.
</DESC_SHORT>

<COMMENTS>
<![CDATA[ 

/*
 * 		BLOCK_NAME_REPLACE()
 *
 * Generated by blockgen
 *
 * Image Termination Block
 * Notes:
 *    This is a block generated from the image terminator template
 *    It will input a sample.
 * 
 *    
 * Programmer: 
 * Date: 
 * Modified: 
 *
 */
]]>
</COMMENTS> 

<DECLARATIONS> 

   	int i,j;
   	image_t img;
   	int fpixel;

</DECLARATIONS> 




<STATES>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> stateVariable </NAME>
		<VALUE> 0 </VALUE>
	</STATE>
</STATES>



<PARAMETERS>
	<PARAM>
		<DEF> Sample Parameter Definition </DEF>
		<TYPE> float </TYPE>
		<NAME> thisSampleParameter </NAME>
		<VALUE> 1999.99 </VALUE>
	</PARAM>
</PARAMETERS>



<INPUT_BUFFERS>
	<BUFFER>
		<TYPE> image_t </TYPE>
		<NAME> x </NAME>
	</BUFFER>
</INPUT_BUFFERS>

<INIT_CODE>
<![CDATA[ 


]]>
</INIT_CODE> 


<MAIN_CODE>
<![CDATA[ 




while(IT_IN(0)) {
       img=x(0);
   
       
       /*
        * This is just to show haow to access the pixels
        */
        
        for(i=0; i< img.height; i++) {
        
           for (j=0; j<img.width; j++) {
              fpixel=img.image_PP[i][j];
#ifdef TEST   
              fprintf(stdout,"%f\n",fpixel); 
#endif   
           
           
           }
        }
  

}
    

]]>
</MAIN_CODE> 

<WRAPUP_CODE>
<![CDATA[ 


]]>
</WRAPUP_CODE> 



</BLOCK> 

