<BLOCK>
<LICENSE>
/*
 * (c) 2006 AUTHOR_NAME 
 */

</LICENSE>
<BLOCK_NAME>
BLOCK_NAME_REPLACE
</BLOCK_NAME> 


<DESC_SHORT>
Add short description here. Will appear in HTML documentation.
</DESC_SHORT>

<COMMENTS>
<![CDATA[ 

/*
 * 		BLOCK_NAME_REPLACE()
 *
 * Generated by blockgen
 *
 * image source
 * Notes:
 *    This is a block generated from the image source template
 *    It will output a small image (200x100) with a 50x50 rectangle
 *    offset at 10,10.
 *
 * 
 *    
 * Programmer: 
 * Date: 
 * Modified: 
 *
 */
]]>
</COMMENTS> 


<INCLUDES>
<![CDATA[ 
#include "dsp.h"
]]>
</INCLUDES> 

<DECLARATIONS> 

	int i,j;
	int sample;
	dsp_floatMatrix_t	matrix;
	dsp_floatMatrix_Pt	matrix_P;
	dsp_floatMatrix_Pt	Dsp_GenMatrix();
	image_t		    img;

</DECLARATIONS> 




<STATES>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> done </NAME>
		<VALUE> FALSE </VALUE>
	</STATE>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> stateVariable </NAME>
		<VALUE> 0 </VALUE>
	</STATE>
</STATES>



<PARAMETERS>
	<PARAM>
		<DEF> Sample Parameter Definition </DEF>
		<TYPE> float </TYPE>
		<NAME> thisSampleParameter </NAME>
		<VALUE> 1999.99 </VALUE>
	</PARAM>
</PARAMETERS>



<OUTPUT_BUFFERS>
	<BUFFER>
		<TYPE> image_t </TYPE>
		<NAME> y </NAME>
	</BUFFER>
</OUTPUT_BUFFERS>

<INIT_CODE>
<![CDATA[ 


]]>
</INIT_CODE> 


<MAIN_CODE>
<![CDATA[ 

	if(done)return(0);
	
	done=TRUE;
	
	/*
	 * Dsp_GenMatrix does the memory allocation for the image matrix
	 */
	matrix_P = Dsp_GenMatrix(200,100,50,50,
                        10,10,
                        128,0,0);

	if(matrix_P==NULL) {
		fprintf(stderr,"BLOCK_NAME_REPLACE: could not generate image \n");
		return(1);
	}


    /*
     * Send image out
	 */

	img.width=matrix_P->width;
	img.height=matrix_P->height;
        img.image_PP=matrix_P->matrix_PP;

	if(IT_OUT(0)) {
				KrnOverflow("BLOCK_NAME_REPLACE",0);
				return(99);
	}
	y(0) = img;
	
			
	

]]>
</MAIN_CODE> 

<WRAPUP_CODE>
<![CDATA[ 


]]>
</WRAPUP_CODE> 



</BLOCK> 

