<BLOCK>
<LICENSE>
/*
 * (c) 2006 AUTHOR_NAME 
 */

</LICENSE>
<BLOCK_NAME>
BLOCK_NAME_REPLACE
</BLOCK_NAME> 


<DESC_SHORT>
Add short description here. Will appear in HTML documentation.
</DESC_SHORT>

<COMMENTS>
<![CDATA[ 

/*
 * 		BLOCK_NAME_REPLACE()
 *
 * Generated by blockgen
 *
 * Integer Termination Block
 * Notes:
 *    This is a block generated from the integer terminator template
 *    It will input a smaple, and print it to the console
 * 
 *    
 * Programmer: 
 * Date: 
 * Modified: 
 *
 */
]]>
</COMMENTS> 

<DECLARATIONS> 

   	int i;
   	int sample;

</DECLARATIONS> 




<STATES>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> stateVariable </NAME>
		<VALUE> 0 </VALUE>
	</STATE>
</STATES>



<PARAMETERS>
	<PARAM>
		<DEF> Sample Parameter Definition </DEF>
		<TYPE> float </TYPE>
		<NAME> thisSampleParameter </NAME>
		<VALUE> 1999.99 </VALUE>
	</PARAM>
</PARAMETERS>



<INPUT_BUFFERS>
	<BUFFER>
		<TYPE> int </TYPE>
		<NAME> x </NAME>
	</BUFFER>
</INPUT_BUFFERS>

<INIT_CODE>
<![CDATA[ 


]]>
</INIT_CODE> 


<MAIN_CODE>
<![CDATA[ 




while(IT_IN(0)) {
   sample=x(0);
   
   fprintf(stdout,"%d\n",sample); 
   


}
    

]]>
</MAIN_CODE> 

<WRAPUP_CODE>
<![CDATA[ 


]]>
</WRAPUP_CODE> 



</BLOCK> 

