<BLOCK>
<LICENSE>
/*
 * (c) 2006 AUTHOR_NAME 
 */

</LICENSE>
<BLOCK_NAME>
gensig
</BLOCK_NAME> 


<DESC_SHORT>
Add short description here. Will appear in HTML documentation.
</DESC_SHORT>

<COMMENTS>
<![CDATA[ 

/*
 * 		gensig()
 *
 * Generated by blockgen
 *
 * Floating point source
 * Notes:
 *    This is a block generated from the floating point source template
 *    It will output numberOfSamples  of samples defined by a parameter.
 *    It outputs the floating point constant 1.0
 *
 * 
 *    
 * Programmer: 
 * Date: 
 * Modified: 
 *
 */
]]>
</COMMENTS> 

<DECLARATIONS> 

	int i,j;

</DECLARATIONS> 




<STATES>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> done </NAME>
		<VALUE> FALSE </VALUE>
	</STATE>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> sampleCount </NAME>
		<VALUE> 0 </VALUE>
	</STATE>
</STATES>



<PARAMETERS>
        <PARAM>
               <DEF> Number of Samples </DEF>
               <TYPE> int </TYPE>
               <NAME> numberOfSamples </NAME>
               <VALUE> 1024 </VALUE>
        </PARAM>
	<PARAM>
		<DEF> Total number of samples to output </DEF>
		<TYPE> int </TYPE>
		<NAME> numberOfSamples </NAME>
		<VALUE> 1000 </VALUE>
	</PARAM>
</PARAMETERS>



<OUTPUT_BUFFERS>
	<BUFFER>
		<TYPE> float </TYPE>
		<NAME> x </NAME>
	</BUFFER>
</OUTPUT_BUFFERS>

<INIT_CODE>
<![CDATA[ 


]]>
</INIT_CODE> 


<MAIN_CODE>
<![CDATA[ 

	if(done)return(0);
	/* 
	 * output a maximum of NUMBER_SAMPLES_PER_VISIT samples to output buffer(s) 
	 */
	for(i=0; i < NUMBER_SAMPLES_PER_VISIT; ++i) {
	   sampleCount++;
	   if(sampleCount == numberOfSamples) {
	       done=TRUE;
	       return(0);
	   }
	   
		
	   /*
	    * ready output buffer for sample
	    * check for overflow
	    */
	   if(IT_OUT(0)) {
				KrnOverflow("gensig",0);
				return(99);
	   }
	   /*
	    * output the sample
	    */
	   x(0)=1.0;
			
			
	}

]]>
</MAIN_CODE> 

<WRAPUP_CODE>
<![CDATA[ 


]]>
</WRAPUP_CODE> 



</BLOCK> 

