


<BLOCK>
<LICENSE>
/*
 * (c) 2006 AUTHOR_NAME
 */

</LICENSE>
<BLOCK_NAME>
processcubed
</BLOCK_NAME>


<DESC_SHORT>
Add short description here. Will appear in HTML documentation.
</DESC_SHORT>

<COMMENTS>
<![CDATA[

/*
 * 		processcubed()
 *
 * Generated by blockgen
 *
 * Floating Point Processor
 * Notes:
 *    This is a block generated from the floating point processor template
 *    It will input a sample, process it and output the processed
 *    sample.
 *
 *    This block simply inputs the sample and outputs it.
 *
 * Programmer:
 * Date:
 * Modified:
 *
 */
]]>
</COMMENTS>

<DECLARATIONS>

   	int i;
   	float sample;
        float xval;

</DECLARATIONS>

<PARAMETERS>
        <PARAM>
               <DEF> Cubic Coeficient </DEF>
               <TYPE> float </TYPE>
               <NAME> a3 </NAME>
               <VALUE> 1.0 </VALUE>
        </PARAM>
        <PARAM>
               <DEF> Quadratic  Coeficient </DEF>
               <TYPE> float </TYPE>
               <NAME> a2 </NAME>
               <VALUE> 1.0 </VALUE>
        </PARAM>
        <PARAM>
               <DEF> Linear Coeficient </DEF>
               <TYPE> float </TYPE>
               <NAME> a1 </NAME>
               <VALUE> 1.0 </VALUE>
        </PARAM>
       <PARAM>
                <DEF> Sample Parameter Definition </DEF>
                <TYPE> float </TYPE>
                <NAME> thisSampleParameter </NAME>
                <VALUE> 1999.99 </VALUE>
       </PARAM>
</PARAMETERS>


<STATES>
	<STATE>
		<TYPE> int </TYPE>
		<NAME> stateVariable </NAME>
		<VALUE> 0 </VALUE>
	</STATE>
</STATES>



<INPUT_BUFFERS>
	<BUFFER>
		<TYPE> float </TYPE>
		<NAME> x </NAME>
	</BUFFER>
</INPUT_BUFFERS>



<OUTPUT_BUFFERS>
	<BUFFER>
		<TYPE> float </TYPE>
		<NAME> y </NAME>
	</BUFFER>
</OUTPUT_BUFFERS>

<INIT_CODE>
<![CDATA[


]]>
</INIT_CODE>


<MAIN_CODE>
<![CDATA[




while(IT_IN(0)) {
       sample=x(0);

   	   /*
	    * ready output buffer for sample
	    * check for overflow
	    */
	   if(IT_OUT(0)) {
				KrnOverflow("processcubed",0);
				return(99);
	   }
	   /*
	    * output the sample
	    */
           xval=sample;
           xval = a1*xval+a2*xval*xval+a3*xval*xval*xval;

	   y(0)=xval;


}


]]>
</MAIN_CODE>

<WRAPUP_CODE>
<![CDATA[


]]>
</WRAPUP_CODE>



</BLOCK>


